### ISSUE TITLE
SimpleConsole compilation fail

### ISSUE THREAD

**Issue by Essarelle** [dtmoodie/EagleEye#25]
Compilation of SimpleConsole fails and throws error:

/home/ubuntu/EagleEye/samples/SimpleConsole/SimpleConsole.cpp: In function 'int main(int, char**)':
/home/ubuntu/EagleEye/samples/SimpleConsole/SimpleConsole.cpp:1579:9: error: 'Cleanup' is not a member of 'mo::ThreadSpecificQueue'
         mo::ThreadSpecificQueue::Cleanup();
         ^

**Comment by Essarelle** [comment]
On Jetson TX1 using master branch

**Comment by Essarelle** [comment]
It does build on x86 with ubuntu though, which is strange

**Comment by dtmoodie** [comment]
That function was added to meta object recently. It may be that meta object was not correctly updated. Try manually updating it.
